### ISSUE TITLE
E5-1650 v2 Can't get up to speed.

### ISSUE THREAD

**Issue by CBAP72** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#12]
Ok.

I've been able to install osx on my z420 but have run into a couple of problems.

1.  Renamed config_IvyCPUs.plist to config.plist - Check
2. Disabled AppleIntelE1000e and enabled IntelMausi. - Check

However, when I tried to generate ssdtPRGen ssdt file for the E5 -1650 v2, I kept getting cpu can't be found in table or some such.

So I ran it on my other mac with  ./ssdtPRGen.sh -p 'E5-1650 v2'  -m MacPr6,1 and copied the resulting aml file over SSDT-CPUM.aml.

As a side, I cannot get Intel Power Gadget to show any data either.

When I run Benchmark 5 I'm getting really low scores.
![Screen Shot 2022-10-14 at 2 25 55 pm](https://user-images.githubusercontent.com/114339784/195765227-0a366e8e-f391-426d-ba8d-22077b9e1be0.png)

Running same in windows:

<img width="625" alt="Geekbench 5" src="https://user-images.githubusercontent.com/114339784/195765328-212d4aaa-e0e2-44e7-a90d-1e3dc32c62a1.PNG">

Any ideas would be appreciated as I'm rather stuck and have been working on this issues for 8 hours.

Cheers,

Carl

**Comment by CBAP72** [comment]
I think removing legacy acpi tables in the bios has fixed the issue.  

But my Multicore speed is still a little low in osx.
![Screen Shot 2022-10-14 at 5 19 36 pm](https://user-images.githubusercontent.com/114339784/195780589-e3c2e43e-b5cf-41f2-9458-cf01472d8608.png)

Is there a way to adjust the multicore performance so it matches Windows 10 or the benchmarks for a 2013 Mac Pro 1650 v2?

I still cannot get intel power gadget to work though.

Cheers,
Carl

**Comment by BillDH2k** [comment]
You have lower scores since you did not have a properly generate ssdt for your CPU. This ssdt must be generate on the same machine you are running or another machine of the same model with the same CPU. These HP Zx20 machines need a special procedure. Re-enable the Legacy ACPI table in the BIOS, and then follow the following steps:

1. Create a ACPI BIOS dump (SysReport).
Use a Debug version of OpenCore (or replace these three files with debug version: BOOTx64.efi, OpenCore.efi, OpenRuntime.efi). Set Config.plist->Root->Misc->Debug->SysReport->True. 
Reboot with the OC usb stick. A SysReport folder will be created on the USB stick, once OC reached the picker.

2. From the SyReport folder, copy ACPI-1.aml and SSDT-2.aml to the Mac desktop. Then, rename: ACPI-1.aml -> ACPI.aml, SSDT-2.aml -> DSDT.aml

3. Run:  ssdtPRGen.sh -mode custom -p 'E5-1560 v2' -x 1 -c 3

Use the new ssdt.aml and re-test your result.

**Comment by CBAP72** [comment]
Thanks for the quick response and fix.
I did generate an ssdt using step 3.  Will try it your way and report back.
Thanks,
Carl

**Comment by CBAP72** [comment]
So once I have the syReport and rename them on my desktop, does ssdtPRGen
find them there automatically?

**Comment by BillDH2k** [comment]
The option "-mode custom" is to tell ssdtPRGen looking for them on desktop, instead of realtime BIOS dump. The CpuDef tables are not stored in DSDT, but in SSDT's. That's why you need to run with '-mode custom'.

**Comment by CBAP72** [comment]
OK, followed those steps with minor changes

ACPI Folder under System Report.

APIC-1.aml -> desktop APIC.aml
SSDT-2.aml ->desktop SSDT.aml

I couldn't find the file names that you gave me so guessing typo?

Created the new ssdt file and overwrote  SSDT-CPUPM.aml in efi area and
rebooted.

SIngle core:  847 which is the same as above.  Multicore 3650 which is a
little lower than above.

Is there a way to overclock a 1 series cpu in opencore?

I REALLY do appreciate your help and suggestions.

Cheers,

Carl

**Comment by BillDH2k** [comment]
Please post your new ssdt here, so I could take a look. Also, you may use AppleIntelInfo.text to check if CPU power management is hitting all states. Check out this thread [here](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/issues/2#issuecomment-1102750954) (Note: the instruction works for Big Sur only, not Monterey. You may use Intel Power Gadget to monitor the CPU activity).

You can also boost the performance by turning on this setting:
config.plist->kernel->quirks->AppleXcpmForceBoost->True

Reboot. Run the test again, 3-4 times in a row. Check your arerage scores.
