### ISSUE TITLE
Stuck in bootloop, unable to get into OpenCore menu

### ISSUE THREAD

**Issue by brampat** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#20]
Hi,

I'm trying to use your EFI on a Z620 with E5-2697 v2 (Ivy, right?) CPU.
Also using Dortania's OpenCore guide to help me get through, but unlucky.
However, I'm unsure if I have everything correctly in place. Here's what I did:
* Checked the BIOS settings as described in your readme, these where all correct by default. I'm currently on a Clover / Catalina OS, which runs smoothly.
* I've used the OpenCore 0.8.4 EFI as a base
* used the Ivy config.plist file (I guess the readme says rename to config.list should be config.plist as with the others, the missing P must be a typo)
* Generated MLB, SystemSerialNumber and SystemUUID using my current Clover tool. Selected MacPro7,1 as hardware profile
* Entered these serials on line 1150 through 1166 in the config.plist file (also changed the SystemProductName to MacPro7,1 just in case)
* Deleted the other config_xxx.plist files
* Didn't remove any of the SSDT files in the ACPI folder, despite them referencing other CPU models. Is that correct?
* Edit: I've tried deleting all the non-2697 SSDT's and removed them (just 2-3 blocks) from the config.plist file, which appears to make a big difference. Still working on it, probably will encounter something new. In the meantime, it may be good idea for others to add this as extra doc / instructions in the readme?

Any help is very very welcome.

**Comment by BillDH2k** [comment]
First of all, you do not need to delete any files, since the loading of these files is controlled by Config.plist . This is very different from Clover. Make sure you use a pure plist editor, like ProperTree, to edit Config.plist. Do not use Clover editor! The Config.plist for Opencore has a different format. 

Is your hardware Z420/620/820? If yes, all you need is a proper SSDT for E5-2697v2 CPU. If you have a working Catalina setup, then you could just use your old SSDT CPU file (just rename the file to SSDT_CPUPM.aml, which is enabled by default in my Config.plist). Anyway, just use my EFI folder, use Config_IvyCPU.plist, copy your CPU SSDT file from your Catalina setup, and add new SS/Board ID's (DO NOT USE Clover editor to modify the plist file). You should have a working setup.

**Comment by BillDH2k** [comment]
Also, if you are trying to boot to existing Catalina, then you need to use my EFI 0.7.1 folder.

**Comment by brampat** [comment]
Thanks. I've been able to get Monterey running. In fact, I'm currently msg-ing from that install. Only thing I've used Clover for is to generate the numbers and copy-pasted them into the plist file, which is in XML format. As a software dev, I didn't see the need for anything "special" to edit XML, so I just used a plain text-editor. I didn't know any special config.plist specific syntax, but removing the non-2697 SSDT's blocks from the plist file apparently did the trick. 

My hardware is a Z620 (see first msg). I'll surely backup the SSDT's from the (old) Catalina EFI, just in case they become handy. I'm not sure yet about my GPU SSDT's. I mean, I obviously booted just fine and have graphics, but I'm not sure if there is still hardware acceleration through GPU missing because of a missing SSDT. If you could comment on that, please let me know. I'll not be able to try it out or respond in the next two weeks though.

Thanks for the response and thanks for this repo in the first place. I don't think I could have managed to get this running without it.

**Comment by BillDH2k** [comment]
You can install IntelPowerGadget ([link](https://www.intel.com/content/www/us/en/developer/articles/tool/power-gadget.html)) to see if you have CPU power management running (CPU speed should be up/down, instead of a const). This tool, however, can only be installed with a single CPU configuration. If you have two CPUs, you need to remove one in order to install it. Once installed, you can put the 2nd CPU back.

If you haven't edited the relevant part in config.plist, then it is loading SSDT_CPUPM.aml for CPU power management table. This file, from my EFI folder, is a copy of SSDT_2670.aml for E5-2670 V1 CPU. You can open and view this aml file with MaciASL tool. It might work for 2697V2, partially, for sure, since not all CPU states are provided. You would still need to generate your own SSDT for this CPU. Follow my guide to bilbo's Z820 instruction, on how to do that.

No GPU ssdt is required (unless you need to spoof the card ID).  What the model of your GPU card?
