### ISSUE TITLE
z820 11.6.5 BIG SUR [Resolved - support for 2687w V2 CPU added to EFI]

### ISSUE THREAD

**Issue by ZZZ8** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#4]
Hi Bill,
thank you very much for the EFI   files.

My PC is HP z820
CPU: E5 2687w v2  X 2
Video Card:  K600

During my installation of BIGSUR 11.6.5 , I encountered a problem.
I used your 2.1v  EFI  file。
Replaced only SSDT-CPUPM.aml 。

But the computer can't boot the system
[EFI.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8493434/EFI.zip)
![6c5c3dd2724692ecfffd380015832eb](https://user-images.githubusercontent.com/40909347/163507910-271ae3e4-a113-4357-9cda-55b510633697.jpg)

**Comment by BillDH2k** [comment]
See my response [here](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/issues/2#issuecomment-1100226448), a solution using Clover loader to fix the booting issue. This Clover EFI, unfortunately, only supports Catalina. Additional works are needed to update to newer version of Clover for Big Sur/Monterey support.

https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/issues/2#issuecomment-1100226448

**Comment by ZZZ8** [comment]
OK thanks  ，I'll try again

**Comment by BillDH2k** [comment]
I have good news for you. I finally figured out how to fix the booting issues for these CPUs, under OpenCore. I've tested with  2667V2 CPUs. But it should also work for your CPUs, with proper patched CpuDef. You can start either with my OC 071 EFI (if you want to boot Catalina/Big Sure), or my 078 EFI (for Big Sur/Monterey). 

You will need the following two files:
- SSDT-1-2687V2-CpuDef.aml (patched Cpu definition to replace Oem CpuDef table)
- SSDT-2687V2.aml    (this is the proper CPUPM file)
[SSDT-1-2687V2-CpuDef.aml.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8507855/SSDT-1-2687V2-CpuDef.aml.zip)
[SSDT-2687V2.aml.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8507857/SSDT-2687V2.aml.zip)

1. Copy both files to your EFI/OC/ACPI folder

2. Add both to config.plist, under Root->ACPI->Add (place both on top, CpuDef 1st).
![ACPI-2687V2-Screen-1](https://user-images.githubusercontent.com/89153638/163868995-2f0c6509-5686-4f7b-9521-b5e1182d146a.png)

3. Disable SSDT-CPUPM.aml, under Root->ACPI->Add (since have are using SSDT-2687V2.aml above)

4. Drop Oem CpuDef table and CpuPm (they were giving us booting issue, thus replace them with our own).
   Root->ACPI->Delete (Copy the entries from the screen shot)

**Update (4/19): Drop CpuPM table is not unnecessary**. So you can leave that item disabled.   

![ACPI-2687V2-Screen-2](https://user-images.githubusercontent.com/89153638/163869201-2fb25fec-fdb2-4638-b4a3-b545902c245f.png)

5. Copy the EFI to your USB EFI partition. Boot up. You can do fresh install or boot from existing install.

Please report back if the above works. If confirmed working, I will add these file to my GitHub.

Thanks!

**Comment by ZZZ8** [comment]
Awesome thank you so much.
 I recently traveled abroad on business
I will test it in the next few days.
 I will send you the test results back. 
Thanks again for your help.

**Comment by BillDH2k** [comment]
I've updated my GutHub EFI. So you may grab a copy from there directly.

**Comment by ZZZ8** [comment]
Sorry for taking so long to give you feedback.
I have bigsur installed. 
It all works fine except the hp thunderbolt card.
Thanks again.

There are some prompts before booting up, I don't know if this is a normal display.

**Comment by ZZZ8** [comment]
![11651106269_ pic_副本](https://user-images.githubusercontent.com/40909347/165654510-7810b44e-d89a-4b71-bb6c-77ef7c16f8ac.jpeg)

**Comment by BillDH2k** [comment]
Everything looks fine. Thunderbird driver is not supported, so you should either disable it BIOS, or just ignore it. Also, you could update to Monterey too, if you wish.

**Comment by ZZZ8** [comment]
Ok, Thanks again for your help。
